apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  # defined which repository should be synced with which k8s cluster
  source:
    repoURL: https://github.com/Edwardwong0826/Argocd-kubernetes-config
    targetRevision: HEAD
    #path is to track specific path or folder
    path: dev
  # can change to any k8s cluster we wanted, it could be k8s cluster where argo cd itself running it or external cluster that argo cd manages
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # By default, changes made to the live cluster will not trigger automated sync and prune
  # and Argo polls Git repository every 3 minutes
  # if selfHeal and prune is set to true, new changes in the repo will trigger immediately
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  # we can yse sync policy to create the namespace if not exist
#    syncOptions:
#      - CreateNamespace=true

# this application yaml only apply for single cluster, if want to work on multiple cluster or multiple env please refer to the video https://www.youtube.com/watch?v=MeU5_k9ssrs

# run kubectl apply -f application.yaml for argo cd start to sync with git repository and deploy to k8s cluster if there is any changes push to repository
# can check in argo cd UI https://localhost:8080/applications?showFavorites=false&proj=&sync=&autoSync=&health=&namespace=&cluster=&labels=
# example we can use CI pipeline to update the image tag or version in deployment.yaml in the source repoURL repository,
